---
- name: INSTALL IIS ON WINDOWS HOST 
  hosts: web
  gather_facts: false
  
  tasks:
    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
