---
- name: SEND REBOOT EMAIL
  hosts: all
  
  tasks:
    - mail:
        host: mail.nortonhealthcare.org
        port: 25
        to: dian.zimmerman@nortonhealthcare.org
        subject: Test email from ansible with body
        body: testing the mail module
        secure: always
      delegate_to: localhost
