---
- name: SEND REBOOT EMAIL
  hosts: all
  
  tasks:
    - mail:
        host: localhost
        port: 25
        to: Dian Zimmerman <dian.zimmerman@nortonhealthcare.org>
        subject: Test email from ansible with body
        body: testing the mail module
