---
- name: STOP SERVICES / REBOOT SERVER / VERIFY SERVICES
  hosts: all
  
  tasks:
    - name: stop the print spooler
      win_service:
        name: Spooler
        state: stopped
      register: service
    
    - name: verify service state
      debug:
        var: service.state
        
    - name: reboot the server
      win_reboot:
        msg: "Reboot initiated by Ansible. You have 1 minute to save your work."
        pre_reboot_delay: 60
        
    - name: start the service if required
      win_service:
        name: Spooler
        state: started
      register: service
      
    - name: verify the service state
      debug:
        var: service.state
