---
- name: REBOOT WINDOWS SERVER
  hosts: all
  
  tasks:
    - name: Set WinRM service to delayed start
      win_service:
        name: WinRM
        start_mode: delayed

    - name: Reboot the server
      win_reboot:
        msg: "Reboot initiated by Ansible"
        pre_reboot_delay: 60
    
    - name: Run a command to verify connectivity
      win_command: whoami.exe
