---
- name: REBOOT WINDOWS SERVER
  hosts: all
  
  tasks:
    - name: Ensure WinRM starts when the system has settled and is ready to work reliably
      win_service:
        name: WinRM
        start_mode: delayed

    - name: Reboot the server
      win_reboot:
        msg: "Reboot initiated by Ansible"
        pre_boot_delay_sec: 120
        test_command: "whoami"
