---
- name: TEST RAW MODULE
  hosts: all 
  
  tasks:
    - name: run ipconfig
      raw: ipconfig
      register: ipconfig
  
    - name: show ipconfig
      debug: var=ipconfig

- name: TEST STAT MODULE
  hosts: all
  
  tasks:
    - name: test stat module on file
      win_stat: path="C:/Windows/win.ini"
      register: stat_file

    - name: show file stats
      debug: var=stat_file
