---
- name: VERIFY A PATCH IS INSTALLED
  hosts: all
  
  tasks:
    - name: use win_shell module to call a powershell command
      win_shell:
        get-hotfix {{ kb_id }}
      register: results
      
    - name: display results
      debug: 
        var: results.stdout
